[[sid-18645210]]

==  Contributing - The Basics


[TIP]
==== 
In this chapter we quickly walk through the basics on contributing; future chapters go into more depth.


==== 


[[sid-18645210_Contributing-TheBasics-Prerequisites]]


=== requisites


|===============
|Java 1.6|Infinispan is baselined on Java 6.0, and is built and tested using Sun Java 6.0.
|Maven 3|The Infinispan build uses Maven, and we recommend using Maven 3.
| Git _(optional)_ |The Infinispan sources are stored in Git. If you don't wish to install Git, you can download source bundles

|===============


[[sid-18645210_Contributing-TheBasics-IssueManagementJIRA]]


=== Issue Management - JIRA

 Infinispan uses JIRA for issue management, hosted on link:$$http://issues.jboss.org/browse/ISPN$$[issues.jboss.org] . You can log in using your normal jboss.org username and password. 

If you need to create a new issue then follow these steps.


. Choose between


*  _Feature Request_ if you want to request an enhancement or new feature for Infinispan 


*  _Bug_ if you have discovered an issue 


*  _Task_ if you wish to request a documentation, sample or process (e.g. build system) enhancement or issue 


.  Then enter a _Summary_ , describing briefly the problem - please try to be descriptive! 


.  You should not set _Priority_ . 


.  Now, enter the version you are reporting an issue against in the _Affects Version_ field, and leave the _Fix Version_ field blank. 


.  In the _Environment_ text area, describe in as much detail as possible your environment (e.g. Java runtime and version, operating system, any network topology which is relevant). 


.  In the _Description_ field enter a detailed description of your problem or request. 


.  If the issue has been discussed on the forums or the mailing list, enter a reference in the _Forum Reference_ field 


.  Finally, hit _Create_ 

[[sid-18645210_Contributing-TheBasics-VersioningGuidelines]]


==== Versioning Guidelines


[WARNING]
==== 
 Only Infinispan contributors should set the _Fix Version_ field. 


==== 


 When setting the _Fix Version_ field for bugs and issues in JIRA, the following guidelines apply: 

Version numbers are defined as MAJOR.MINOR.MICRO.MODIFIER.  For example, 4.1.0.BETA1 would be:


|===============
|MAJOR|4
|MINOR|1
|MICRO|0
|MODIFIER|BETA1

|===============


 If the issue relates to a Task or Feature Request, please ensure that the .FINAL version is included in the Fixed In field.  For example, a new feature should contain 4.1.0.BETA1, 4.1.0.FINAL if it is new for 4.1.0 and was first made public in BETA1.  For example, see link:$$https://issues.jboss.org/browse/ISPN-299$$[ISPN-299] . 

 If the issue relates to a bug which affected a previous FINAL version, then the Fixed In field should also contain the .FINAL version which contains the fix, in addition to any ALPHA, BETA or CR release.  For example, see link:$$https://issues.jboss.org/browse/ISPN-546$$[ISPN-546] . If the issue pertains to a bug in the current release, then the .FINAL version should not be in the Fixed In field.  For example, a bug found in 4.1.0.ALPHA2 (but not in 4.1.0.ALPHA1) should be marked as fixed in 4.1.0.ALPHA3, but not in 4.1.0.FINAL.  For example, see link:$$https://issues.jboss.org/browse/ISPN-416$$[ISPN-416] . 

[[sid-18645210_Contributing-TheBasics-SourcecontrolGit]]


=== Source control - Git

 Infinispan uses link:$$http://git-scm.com$$[git] , hosted on link:$$http://github.com$$[GitHub] , for version control. You can find the upstream git repository at link:$$https://github.com/infinispan$$[] . To clone the repository: 


----

$ git clone git@github.com:infinispan/infinispan.git

----

or to clone your fork:


----

$ git clone git@github.com:YOUR_GITHB_USERNAME/infinispan.git

----

 For more information, read <<sid-18645215,the Git chapter>> . 

[[sid-18645210_Contributing-TheBasics-SettingupyourIDE]]


==== Setting up your IDE

Maven supports generating IDE configuration files for easy setup of a project. Tested are Eclipse, IntelliJ IDEA and Netbeans.

Before we import the project, we need to clone the project as described above.

[[sid-18645210_Contributing-TheBasics-Eclipse]]


===== Eclipse


.  Install the m2eclipse plugin if you have not already installed it. Eclipse is including it since version "Indigo" 3.7, for older versions follow instructions at link:$$http://eclipse.org/m2e/$$[] . 


.  Import the Infinispan maven project. Select File -&gt; Import in your eclipse workbench. Select the Existing Maven Project importer. 


.TODO InformalFigure image title empty
image::[]


.  Select the root directory of your Infinispan checkout. 


.TODO InformalFigure image title empty
image::[]


. Select Infinispan modules that you want to import.


. Finally, from Infinispan 5.0 onwards, annotation processing is used to allow log messages to be internationalized. This processing can be done directly from Eclipse as part of compilation but it requires some set up:


.  Open the properties for infinispan-core and locate Annotation Processing 


.  Tick Enable project specific settings 


.  Enter target/generated-sources/annotations as the Generated source directory 


.TODO InformalFigure image title empty
image::[]

 Code Formatting. From the menu Window-&gt;Preferences-&gt; select Java -&gt; Code Style -&gt; Formatter. Import link:$$https://github.com/infinispan/infinispan/blob/master/ide-settings/eclipse/formatter.xml$$[formatter.xml] Code template. From the menu Window-&gt;Preferences-&gt; select Java -&gt; Code Style -&gt;  Code Templates. Import link:$$https://github.com/infinispan/infinispan/blob/master/ide-settings/eclipse/codetemplates.xml$$[codetemplates.xml] 

 As some modules use Scala, it's worth installing the link:$$http://www.scala-lang.org/node/94$$[Scala tools] . 

[[sid-18645210_Contributing-TheBasics-IntelliJIDEA]]


===== IntelliJ IDEA

IntelliJ's built-in Maven support is the best way to go. From IntelliJ 9 onwards, this is a robust and reliable mechanism to import a project from Maven.


. Create a new project in IntelliJ

 
.TODO InformalFigure image title empty
image::[]

 


. And choose to import the project from an external model

 
.TODO InformalFigure image title empty
image::[]

 


. When asked, point the wizard to the directory created when you cloned the repository


. Make sure that the check-boxes for "Search for projects recursively" and "Create module groups for multi-module Maven projects" are checked.


. Just follow through the rest of the steps in the wizard and you're good to go.


. Finally, from Infinispan 5.0 onwards, annotation processing is used to allow log messages to be internationalized. This processing can be done directly from IntelliJ as part of compilation but it requires some set up:


*  Go to "Preferences/Compiler/Annotation Processor" and click on _Enable annotation processing_ 


*  Add an annotation processor with "Processor FQN Name" as org.jboss.logging.LoggingToolsProcessor 


* In "Processed Modules", add all modules except the root and the parent modules.

 
.TODO InformalFigure image title empty
image::[]

 

IntelliJ has built in Scala support, just make sure the Scala module is installed.

 IntelliJ related code style jar is at link:$$https://github.com/infinispan/infinispan/blob/master/ide-settings/intellij/IntelliJ_IDEA_Code_Style.jar$$[idea-code-style.jar] 

[[sid-18645210_Contributing-TheBasics-BuildMaven]]


=== Build - Maven

 Infinispan uses link:$$http://maven.apache.org/$$[Maven] for builds. Make sure you have Maven 3 installed, and properly configured. For more information, read <<sid-18645215,the Maven chapter>> . 

[[sid-18645210_Contributing-TheBasics-ContinuousIntegrationJenkinsonCloudbees]]


==== Continuous Integration - Jenkins on Cloudbees

 Infinispan uses Jenkins on Cloudbees for continuous integration. Jenkins polls GitHub for updates and runs whenever updates are available. For more information view link:$$http://www.jboss.org/infinispan/build.html$$[the project site] . 

[[sid-18645210_Contributing-TheBasics-TestingTestNG]]


=== Testing - TestNG

 Infinispan uses TestNG for unit and functional tests, and all Infinispan tests are run in parallel. For more information see <<sid-18645211,the Test Suite chapter>> ; this chapter gives advice on writing tests which can safely execute in parallel. 

[[sid-18645210_Contributing-TheBasics-CommunicatingwithotherInfinispancontributors]]


=== Communicating with other Infinispan contributors

 Infinispan contributors use a mix of link:$$http://www.jboss.org/infinispan/mailinglists$$[mailings lists] and link:$$http://www.jboss.org/infinispan/community.html$$[IRC] to communicate ideas and designs, with more detailed designs often making their way into link:$$http://community.jboss.org/$$[wiki pages] . 

[[sid-18645210_Contributing-TheBasics-StyleRequirements]]


=== Style Requirements

 Infinispan uses the link:$$http://en.wikipedia.org/wiki/Indent_style#K.26R_style$$[K&amp;R code style] for all Java source files, with two exceptions: 


* use 3 spaces instead of a tab character for indentations.


* braces start on the same line for class, interface and method declarations as well as code blocks.

 In addition, sure all link:$$http://en.wikipedia.org/wiki/Newline$$[new line characters] used must be LF (UNIX style line feeds). Most good IDEs allow you to set this, regardless of operating system used. 

 All patches or code committed must adhere to this style. Code style settings which can be imported into IntelliJ IDEA and Eclipse are committed in the project sources, in link:$$https://github.com/infinispan/infinispan/blob/master/ide-settings/$$[ide-settings] . 

[[sid-18645210_Contributing-TheBasics-Spelling]]


==== Spelling

 Ensure correct spelling in code, comments, Javadocs, etc. (use _American English_ spelling). It is recommended that you use a spellchecker plugin for your IDE. 

[[sid-18645210_Contributing-TheBasics-Licenseheader]]


==== License header

 All source files must have up-to-date license headers as described in link:$$http://community.jboss.org/docs/16352$$[Copyright Ownership and Licenses] . Never remove existing headers or copyrights. 

[[sid-18645210_Contributing-TheBasics-Checkincomments]]


==== Check-in comments

 Please ensure any commit comments use link:$$https://docs.jboss.org/author/pages/viewpage.action?pageId=18645271_InfinispanandGitHub-Comments$$[this format] if related to a task or issue in JIRA. This helps JIRA pick out these checkins and display them on the issue, making it very useful for back/forward porting fixes. If your comment does not follow this format, your commit may not be merged into upstream. 

[[sid-18645210_Contributing-TheBasics-Configuration]]


=== Configuration

 Infinispan offers both programmatic configuration and XML configuration. For more information read the <<sid-18645216,Configuration>> chapter. 

[[sid-18645210_Contributing-TheBasics-Logging]]


=== Logging

 From Infinispan 5.0 onwards, Infinispan uses JBoss Logging to abstract over the logging backend. Infinispan supports localization of log message for categories of INFO or above as explained in link:$$http://community.jboss.org/docs/16738$$[the JBoss Logging guidelines] . As a developer, this means that for each INFO , WARN , ERROR , FATAL message your code emits, you need to modify the Log class in your module and add an explicit method for it with the right annotations. For example: 


----

@LogMessage(level = INFO)
@Message(value = "An informative message: %s - %s", id = 600)
void anInformativeMessage(String param1, String param2);

----

 And then, instead of calling log.info(...) , you call the method, for example log.anInformativeMessage(param1, param2) . If what you're trying to log is an error or similar message and you want an exception to be logged as cause, simply use @Cause annotation, example: 


----

@LogMessage(level = ERROR)
@Message(value = "An error message: %s", id = 600)
void anErrorMessage(String param1, @Cause IllegalStateException e);

----

The last thing to figure out is which id to give to the message. Each module that logs something in production code that could be internationalized has been given an id range, and so the messages should use an available id in the range for the module where the log call resides. Here are the id range assignments per module:

[options="header"]
|===============
|Module name|Id range
|core|1 - 1000
|tree|1001 - 2000
|bdbje cache store|2001 - 3000
|cassandra cache store|3001 - 4000
|hotrod client|4001 - 5000
|server core|5001 - 6000
|server hotrod|6001 - 7000
|cloud cache store|7001 - 8000
|jdbc cache store|8001 - 9000
|jdbm cache store|9001 - 10000
|remote cache store|10001 - 11000
|server memcached|11001 - 12000
|server rest|12001 - 13000
|server websocket|13001 - 14000
|query|14001 - 15000
|lucene directory|15001 - 16000
|rhq plugin|16001 - 17000
|cdi integration|17001 - 18000

|===============



[NOTE]
==== 
You will need to enable annotation processing in order to be able to compile Infinispan and have the logger implementation generated.


==== 


